config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :clients
  resources :typeinmus
  resources :states
  get 'welcome/index'


  root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/state.rb
class State < ApplicationRecord

has_one :Typeinmu
belongs_to :Client


end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
    #@statetype = Typeinmu.where(:id)
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :typeofstate, :area, :countfloor, :countRoom, :address, :typeinmu_id)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_with(model: state, local: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-md-2">
    <%= form.label :Nombre %>
    <%= form.text_field :name, id: :state_name, :class =>'form-control' %>
  </div>

  <div class="field col-md-2">
    <%= form.label :Tipo %>
    <%= form.select :typeofstate  , options_for_select(Typeinmu.all.map{|s|[s.name, s.id ]}),{},{:class=> "form-control" } %>
  </div>

  <div class="field col-md-1">
    <%= form.label :Area %>
    <%= form.number_field :area, id: :state_area,  :class =>'form-control'%>
  </div>

  <div class="field col-md-2">
    <%= form.label :Cantidad_de_Pisos %>
    <%= form.number_field :countfloor, id: :state_countfloor, :class =>'form-control' %>
  </div>

  <div class="field col-md-1">
    <%= form.label :CUARTOS %>
    <%= form.number_field :countRoom, id: :state_countRoom, :class =>'form-control' %>
  </div>

  <div class="field col-md-2">
    <%= form.label :Dirección %>
    <%= form.text_field :address, id: :state_address, :class =>'form-control' %>
  </div>

  <div class="actions col-md-2 cold-xs-2">
    <%= form.submit 'Crear Inmueble', :class =>'btn btn-default'%>
  </div>
<% end %><br>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Mostrar', @state %> |
<%= link_to 'Atras', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inmuebles</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo de Inmuebles</th>
      <th>Area</th>
      <th>Cantidad de Pisos</th>
      <th>Cantidad de Cuartos</th>
      <th>Dirección</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= Typeinmu.select('name').where('id = State.id') %></td>
        <td><%= state.area %></td>
        <td><%= state.countfloor %></td>
        <td><%= state.countRoom %></td>
        <td><%= state.address %></td>
        <td><%= link_to 'Ver', state %></td>
        <td><%= link_to 'Editar', edit_state_path(state) %></td>
        <td><%= link_to 'Dar de Baja', state, method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/states/new.html.erb
<h1>Nuevo Inmueble</h1><br>

<%= render 'form', state: @state %>

<%= link_to 'Inmuebles', states_path, :class =>' col-md-1 btn btn-default' %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @state.typeofstate %>
</p>

<p>
  <strong>Area:</strong>
  <%= @state.area %>
</p>

<p>
  <strong>Countfloor:</strong>
  <%= @state.countfloor %>
</p>

<p>
  <strong>Countroom:</strong>
  <%= @state.countRoom %>
</p>

<p>
  <strong>Address:</strong>
  <%= @state.address %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>