config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :clients
  resources :typeinmus
  resources :states
  get 'welcome/index'


  root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord

      has_one :State
      belongs_to :Rental
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :year, :genere, :stateclient, :pic)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-md-2">
    <%= form.label :Nombre %>
    <%= form.text_field :name, id: :client_name, :class => 'form-control' %>
  </div>

  <div class="field col-md-2">
    <%= form.label :Edad %>
    <%= form.number_field :year, id: :client_year, :class => 'form-control' %>
  </div>

  <div class="field col-md-2">
    <%= form.label :Genero %>
    <%= form.text_field :genere, id: :client_genere, :class => 'form-control' %>
  </div>

  <div class="field col-md-2">
    <%= form.label :Estado %>
    <%= form.text_field :stateclient, id: :client_stateclient, :class => 'form-control' %>
  </div>

  <!--<div class="field col-md-2">
    <%= form.label :pic %>
    <%= form.text_field :pic, id: :client_pic, :class => 'form-control' %>
  </div>-->

  <div class="actions col-md-2">
    <%= form.submit "Crear", :class => 'btn btn-default'%>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Genero</th>
      <th>Estado</th>
      <!--<th>Pic</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.year %></td>
        <td><%= client.genere %></td>
        <td><%= client.stateclient %></td>
        <!--<td><%= client.pic %></td>-->
        <td><%= link_to 'Ver', client, :class => 'btn btn-default' %></td>
        <td><%= link_to 'Editar', edit_client_path(client), :class => 'btn btn-default' %></td>
        <td><%= link_to 'Dar de baja', client, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<h1>NUEVO INQUILINO</h1>
<br>
<%= render 'form', client: @client %>

<%= link_to 'Lista de Clientes', clients_path, :class => 'btn btn-default col-md-2' %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @client.year %>
</p>

<p>
  <strong>Genere:</strong>
  <%= @client.genere %>
</p>

<p>
  <strong>Stateclient:</strong>
  <%= @client.stateclient %>
</p>

<p>
  <strong>Pic:</strong>
  <%= @client.pic %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>