config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :clients
  resources :typeinmus
  resources :states
  get 'welcome/index'


  root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rental.rb
class Rental < ApplicationRecord

  has_one :Client
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:client, :type_rental, :room, :type_state, :room_state)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_with(model: rental, local: true) do |form| %>
  <% if rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Cliente %><br>
    <%= form.select :client, options_for_select(Client.all.map{|s|[s.name, s.id ]}),{},{:class=> "form-control",:style=>"float:left" } %><br>

  </div>

  <div class="field"><br>
    <%= form.label :Edificio %><br>
    <%= form.select :type_rental  , options_for_select(State.all.map{|s|[s.name, s.id ]}),{},{:class=> "form-control",:style=>"float:left" } %><br>
  </div>

  <div class="field"><br>
    <%= form.label :Cuartos %><br>
    <%= form.text_field :room, id: :rental_time, :class=> "form-control" %><br>
  </div>

  <div class="field"><br>
    <%= form.label :Cheque %><br>
    <%= form.check_box :type_state, id: :rental_type_state, :class=> "form-control" %><br>
  </div>

  <div class="field"><br>
    <%= form.label :Tiempo_De_Renta %>
    <%= form.number_field :room_state, id: :rental_time_state, :class=> "form-control" %><br>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alquiler</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Clientes</th>
      <th>Edificio</th>
      <th>Cuartos</th>
      <th>ACTIVO </th>
      <th>Tiempo de Renta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.client %></td>
        <td><%= rental.type_rental %></td>
        <td><%= rental.room %></td>
        <td><%= rental.type_state %></td>
        <td><%= rental.room_state %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>Nueva Renta</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @rental.client %>
</p>

<p>
  <strong>Type rental:</strong>
  <%= @rental.type_rental %>
</p>

<p>
  <strong>room:</strong>
  <%= @rental.room %>
</p>

<p>
  <strong>Type state:</strong>
  <%= @rental.type_state %>
</p>

<p>
  <strong>Time state:</strong>
  <%= @rental.room_state %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>