config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :clients
  resources :typeinmus
  resources :states
  get 'welcome/index'


  root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alert.html.erb
<% if notice %>
<p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
<p class="alert alert-danger"><%= alert %></p>
  <% end %>

app/views/layouts/_main.html.erb
  <div>
    <% if current_user.email == 'admin@inmu.com' %>
    <div class="col-md-9">


  <%= link_to 'Registra un nuevo Tipo de Inmueble', new_typeinmu_path, :class => 'btn btn-default navbar-btn' %>
  <%= link_to 'Registra un nuevo Inmueble', new_state_path, :class => 'btn btn-default navbar-btn' %>
  <%= link_to 'Registra un nuevo Inquilino', new_client_path, :class => 'btn btn-default navbar-btn'%>
  <%= link_to 'Registra un nuevo Alquiler', new_rental_path, :class => 'btn btn-default navbar-btn'%>

   </div>
<% else %>
  <%= link_to 'Registra un nuevo Inmueble', new_state_path %>

<% end %>
</div>
<div class=" col-md-6">
<%= link_to "Vuelvo al inicio", controller: '/welcome', action: 'index', :class => "btn btn-default navbar-btn" %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>




    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="">  <%=link_to 'INICIO', :controller => 'welcome', :action => 'index'%><span class="sr-only">(current)</span></li>
        <li class=""><%=link_to 'Rentas', rentals_path%><span class="sr-only">(current)</span></li>
        <li class=""><%=link_to 'Clientes', clients_path%><span class="sr-only">(current)</span></li>
        <li class=""><%=link_to 'Inmuebles', states_path%><span class="sr-only">(current)</span></li>

        </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/sesionnav'%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sesionnav.html.erb
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logeeado por <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'btn btn-default navbar-btn' %>
  <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, :class => 'btn btn-default navbar-btn'  %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inmu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<% if user_signed_in? %>
    <%= render 'layouts/nav'%>
    
<% end %>
  </head>

  <body>

    <%= render 'layouts/alert'%>
    <%= yield %>

<% if user_signed_in?%>
    <%= render 'layouts/main'%>

<% end %>

  </body>
</html>